config/routes.rb
Feedcharlotte::Application.routes.draw do

  resources :changes
  resources :feeding_schedules
  resources :sleeping_schedules do
    collection do
      post :end_sleep
    end
  end

  root :to => "home#index"
end

app/models/change.rb
class Change < ActiveRecord::Base
  attr_accessible :pee, :poo

  validate :at_least_pee_or_poo

  before_save :set_time

  def set_time
    self.time = DateTime.now if self.time.nil?
  end

  private

  def at_least_pee_or_poo
    if !(pee || poo)
      errors[:base] << "Must have either pee or poo"
    end
  end
end

app/models/feeding_schedule.rb
class FeedingSchedule < ActiveRecord::Base
  attr_accessible :bottled, :left, :start

  validates_presence_of :start
  validates :bottled, :inclusion => {:in => [true, false]}
end

app/models/sleeping_schedule.rb
class SleepingSchedule < ActiveRecord::Base
  attr_accessible :end

  before_save :start_time

  def self.finish_sleep?
    SleepingSchedule.last && SleepingSchedule.last.end.blank?
  end

  private

  def start_time
    self.start = DateTime.now unless self.start.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/changes_controller.rb
class ChangesController < ApplicationController

  def index
    @changings = Change.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @changings }
    end
  end

  def edit
    @changing = Change.find(params[:id])
  end

  def update
    @changing = Change.find(params[:id])
    @changing.update_attributes!(params[:change])
    redirect_to changes_path
  end

  def show
    @changing = Change.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @changing }
    end
  end

  def create
    Change.create!(params[:change])
    redirect_to root_path
  end

  def destroy
    @changing = Change.find(params[:id])
    @changing.destroy

    respond_to do |format|
      format.html { redirect_to changings_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/changings_controller.rb
class ChangingsController < ApplicationController

  def index
    @changings = Changing.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @changings }
    end
  end

  def show
    @changing = Changing.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @changing }
    end
  end

  def create
    Changing.create!
    render nothing: true
  end

  def destroy
    @changing = Changing.find(params[:id])
    @changing.destroy

    respond_to do |format|
      format.html { redirect_to changings_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/feeding_schedules_controller.rb
class FeedingSchedulesController < ApplicationController

  def index
    @feedings = FeedingSchedule.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @feedings }
    end
  end

  def show
    @feeding = FeedingSchedule.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @feeding }
    end
  end

  def create
    feeding = FeedingSchedule.new(params[:feeding_schedule])
    feeding.end = DateTime.now
    feeding.save!
    redirect_to root_path
  end

  def destroy
    @feeding = FeedingSchedule.find(params[:id])
    @feeding.destroy

    respond_to do |format|
      format.html { redirect_to feedings_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/feedings_controller.rb
class FeedingsController < ApplicationController

  def index
    @feedings = Feeding.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @feedings }
    end
  end

  def show
    @feeding = Feeding.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @feeding }
    end
  end

  def create
    Feeding.create!
    render nothing: true
  end

  def destroy
    @feeding = Feeding.find(params[:id])
    @feeding.destroy

    respond_to do |format|
      format.html { redirect_to feedings_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @feedings_count = FeedingSchedule.count
    @changings_count = Change.count
    @sleepings_count = SleepingSchedule.count
    @can_end_sleep = SleepingSchedule.finish_sleep?
    @feeding = FeedingSchedule.new
    @change = Change.new
    @last_breast_feed = FeedingSchedule.where(bottled: false).order("id desc").first
  end
end

app/controllers/sleeping_schedules_controller.rb
class SleepingSchedulesController < ApplicationController

  def new
    @sleeping = SleepingSchedule.new
  end

  def index
    @sleepings = SleepingSchedule.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sleepings }
    end
  end

  def show
    @sleeping = SleepingSchedule.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sleeping }
    end
  end

  def create
    SleepingSchedule.create!
    render nothing: true
  end

  def edit
    @sleeping = SleepingSchedule.find(params[:id])
  end

  def end_sleep
    SleepingSchedule.last.update_attribute(:end, DateTime.now)
    render nothing: true
  end

  def destroy
    @sleeping = SleepingSchedule.find(params[:id])
    @sleeping.destroy

    respond_to do |format|
      format.html { redirect_to sleepings_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sleepings_controller.rb
class SleepingsController < ApplicationController

  def index
    @sleepings = Sleeping.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sleepings }
    end
  end

  def show
    @sleeping = Sleeping.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sleeping }
    end
  end

  def create
    Sleeping.create!
    render nothing: true
  end

  def destroy
    @sleeping = Sleeping.find(params[:id])
    @sleeping.destroy

    respond_to do |format|
      format.html { redirect_to sleepings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/changes/_form.html.erb
<%= form_for(@changing) do |f| %>
  <% if @changing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@changing.errors.count, "error") %> prohibited this changing from being saved:</h2>

      <ul>
      <% @changing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p><%= f.label :pee %><%= f.check_box :pee %>
  <p><%= f.label :poo %><%= f.check_box :poo %>
  <p><%= f.label :time %><%= f.text_field :time %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/changes/edit.html.erb
<h1>Editing changing</h1>

<%= render 'form' %>

<%= link_to 'Show', @changing %> |
<%= link_to 'Back', changes_path %>

app/views/changes/index.html.erb
<h1>Listing changings</h1>

<table>
  <tr>
    <th>Pee
    <th>Poo
    <th>Timestamp
    <th>
    <th>
    <th>
<% @changings.each do |changing| %>
  <tr>
    <td><%= changing.pee ? "X" : "" %>
    <td><%= changing.poo ? "X" : "" %>
    <td><%= changing.time.strftime("%Y-%m-%d %H:%M:%S")%>
    <td><%= link_to 'Show', changing %>
    <td><%= link_to 'Edit', edit_change_path(changing) %>
    <td>(<%= link_to 'x', changing, method: :delete, data: { confirm: 'Are you sure?' } %>)
<% end %>
</table>

<br>

<%= link_to 'New Changing', new_change_path %>

app/views/changes/new.html.erb
<h1>New changing</h1>

<%= render 'form' %>

<%= link_to 'Back', changes_path %>

app/views/changes/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_change_path(@changing) %> |
<%= link_to 'Back', changes_path %>

app/views/feeding_schedules/_form.html.erb
<%= form_for(@feeding) do |f| %>
  <% if @feeding.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feeding.errors.count, "error") %> prohibited this feeding from being saved:</h2>

      <ul>
      <% @feeding.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feeding_schedules/edit.html.erb
<h1>Editing feeding</h1>

<%= render 'form' %>

<%= link_to 'Show', @feeding %> |
<%= link_to 'Back', feedings_path %>

app/views/feeding_schedules/index.html.erb
<h1>Listing feedings</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @feedings.each do |feeding| %>
  <tr>
    <td><%= link_to 'Show', feeding %></td>
    <td><%= link_to 'Edit', edit_feeding_path(feeding) %></td>
    <td><%= link_to 'Destroy', feeding, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Feeding', new_feeding_path %>

app/views/feeding_schedules/new.html.erb
<h1>New feeding</h1>

<%= render 'form' %>

<%= link_to 'Back', feedings_path %>

app/views/feeding_schedules/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_feeding_path(@feeding) %> |
<%= link_to 'Back', feedings_path %>

app/views/home/_changing_section.html.erb
<%= form_for change do |f| %>
  <%= f.label :pee %>
  <%= f.check_box :pee %>
  <%= f.label :poo %>
  <%= f.check_box :poo %>
  <%= f.submit 'Save' %>
<% end %>

app/views/home/_feeding_section.html.erb
<% content_for :head do %>
<style>
  .block-section {
    height: 45px;
  }
  .bi-select {
    height: 35px;
    width: 45px;
  }
</style>

<% end %>

<ul class="segmented-controller">
  <li><a class="" href="#bottled-section">Bottled</a>
  <li><a class="" href="#breast-section">Breast</a>
</ul>
<%= form_for feeding do |f| %>
  <%= f.hidden_field :bottled %>
  <ul class="inset list">
    <li id="bottled-section" class="feed-select segmented-controller-item">
    <li id="breast-section" class="feed-select segmented-controller-item">
      <% if @last_breast_feed %>
      <div>Last Side: <%= @last_breast_feed.left ? "L" : "R" %>
      <% end %>
      <div class="block-section">
        <%= f.label :left %>
        <%= f.check_box :left %>
      </div>
      <div class="block-section">
        <a class='feed-start bi-select button'>Start</a>
      </div>
    </li>
  </ul>
  <%= f.hidden_field :start %>
<% end %>

<% content_for :script do %>
<script>
  $('.bi-select').click(function() {
    $("#feeding_schedule_bottled").val("false");
    $('.bi-select').removeClass('active');
    $(this).addClass('active');
    $('.feed-start').show();
  });

  $('.feed-start').click(function() {
    if ($(this).text() == 'Start') {
      $('#feeding_schedule_start').val(new Date());
      $(this).text('End');
    } else {
      $(this).closest('form').submit();
    }
  });
</script>
<% end %>

app/views/home/index.html.erb
<% content_for :head do %>
<style>
  <% if !@can_end_sleep %>
    #end-sleep { display: none; }
  <% end %>
  .list .button {
    position: relative;
    right: auto;
    float: left;
  }
</style>
<% end %>

<ul class="segmented-controller">
  <li><a href="#feed-section"><span class='count'><%= @feedings_count %></span>Feed</a>
  <li><a href="#change-section"><span class='count'><%= @changings_count %></span>Change</a>
  <li><a href="#sleep-section"><span class='count'><%= @sleepings_count %></span>Sleep</a>
</ul>
<ul class="inset list">
  <li id="feed-section" class="segmented-controller-item active">
    <%= render "feeding_section", feeding: @feeding, last_breast_feed: @last_breast_feed %>
  </li>
  <li id="change-section" class="segmented-controller-item">
    <%= render "changing_section", change: @change %>
  </li>
  <li id="sleep-section" class="segmented-controller-item">
    <a id='end-sleep' class='button'>End</a>
    <a id='start-sleep' class='button'>Start</a>
  </li>
</ul>

<% content_for :script do %>
<script>
  var token = "<%= form_authenticity_token %>";

  $("#start-sleep").click(function() {
    var a = $(this);
    $.post("<%= sleeping_schedules_path %>", {authenticity_token: token}, function() {
      var span = a.find('span');
      span.text(parseInt(span.text()) + 1);
      $("#end-sleep").show();
    });
  });

  $("#end-sleep").click(function() {
    var a = $(this);
    $.post("<%= end_sleep_sleeping_schedules_path %>", {authenticty_token: token}, function() {
      a.hide();
    });
  });
</script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Feedcharlotte</title>
  <%= stylesheet_link_tag *['common', 'ratchet'].concat(@page_css || []).uniq %>
  <%= yield :head %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width = device-width">
</head>
<body>
  <header class="bar-title">
    <h1 class="title"><a href="<%= root_path %>">Charlotte Tracker</a></h1>
  </header>
  <div class="content">
    <%= yield %>
  </div>
  <script src="http://code.jquery.com/jquery-1.8.2.min.js"></script>
  <%= javascript_include_tag *['ratchet'].concat(@page_js || []).uniq %>
  <%= yield :script %>
</body>
</html>

app/views/sleeping_schedules/_form.html.erb
<%= form_for(@sleeping) do |f| %>
  <% if @sleeping.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sleeping.errors.count, "error") %> prohibited this sleeping from being saved:</h2>

      <ul>
      <% @sleeping.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sleeping_schedules/edit.html.erb
<h1>Editing sleeping</h1>

<%= render 'form' %>

<%= link_to 'Show', @sleeping %> |
<%= link_to 'Back', sleeping_schedules_path %>

app/views/sleeping_schedules/index.html.erb
<h1>Listing sleepings</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sleepings.each do |sleeping| %>
  <tr>
    <td><%= link_to 'Show', sleeping %></td>
    <td><%= link_to 'Edit', edit_sleeping_schedule_path(sleeping) %></td>
    <td><%= link_to 'Destroy', sleeping, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sleeping', new_sleeping_schedule_path %>

app/views/sleeping_schedules/new.html.erb
<h1>New sleeping</h1>

<%= render 'form' %>

<%= link_to 'Back', sleeping_schedules_path %>

app/views/sleeping_schedules/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_sleeping_schedule_path(@sleeping) %> |
<%= link_to 'Back', sleeping_schedules_path %>

app/views/sleepings/edit.html.erb
<h1>Editing sleeping</h1>

<%= render 'form' %>

<%= link_to 'Show', @sleeping %> |
<%= link_to 'Back', sleepings_path %>

app/views/sleepings/index.html.erb
<h1>Listing sleepings</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sleepings.each do |sleeping| %>
  <tr>
    <td><%= link_to 'Show', sleeping %></td>
    <td><%= link_to 'Edit', edit_sleeping_path(sleeping) %></td>
    <td><%= link_to 'Destroy', sleeping, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sleeping', new_sleeping_path %>